### ISSUE TITLE
Stop or Play Next

### ISSUE THREAD

**Issue by karmsingh** [calmcom/PersistentStreamPlayer#4]
Hi, some background, I am using the player in a music app as the music player. So skip songs in playlists etc.. I have integrated the persistent stream player into our project and it works so far as:
- Play a stream, persistence, download etc.
- Pause 

However, I can't see in the documentation how to skip to another song/track? I can only see the destroy method?

Any guidance appreciated!

**Comment by tsheaff** [comment]
Hey @karmsingh thanks for explaining this use-case.

The library currently has no concept of tracks. Each instance of `PersistentStreamPlayer` will play exactly one file from one URL.  If you want to have multiple tracks, you'll have to either handle that outside the library, or create a (non-breaking) pull request that makes the `PersistentStreamPlayer` support multiple URLs (e.g. and array).

**Comment by karmsingh** [comment]
Thanks for your input. I understand and will create something for this purpose. In order to save some time can you tell me what is the underlying AV module this player depends on? Is it MPMovie or something...I would like to see if there is a built in method to stop/skip I can send. Thanks again

**Comment by tsheaff** [comment]
It uses `AVPlayer`. See [here](https://github.com/calm/PersistentStreamPlayer/blob/master/PersistentStreamPlayer.m#L72)

**Comment by karmsingh** [comment]
great. thanks!

**Comment by karmsingh** [comment]
FYI - AVPlayer doesn't have a stop function see here: http://stackoverflow.com/questions/17831764/how-to-stop-a-video-in-avplayer
